security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Utilise 'email' si tu veux que les utilisateurs se connectent avec leur e-mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator  # 🔥 Ajout de l'entry_point ici
            form_login:
                login_path: app_login       # Route vers la page de connexion
                check_path: app_login       # Route vers l'action de vérification des identifiants
                default_target_path: app_index # Page vers laquelle l'utilisateur est redirigé après connexion
                enable_csrf: true          # Active la protection CSRF
            logout:
                path: app_logout           # Route de déconnexion
            custom_authenticator: App\Security\LoginFormAuthenticator  # Ton authenticator personnalisé

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }       # Page de connexion accessible sans être connecté
        - { path: ^/register, roles: PUBLIC_ACCESS }    # Page d'inscription accessible sans être connecté
        - { path: ^/, roles: ROLE_USER }                # Protège toutes les autres pages (nécessite la connexion)

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        firewalls:
            main:
                lazy: true
                provider: users_in_memory
                custom_authenticator: App\Security\LoginFormAuthenticator
                logout:
                    path: app_logout
